import type { Equipamento, Projeto } from './types'

export const MOCK_PROJETOS: Projeto[] = [
  { id: 'proj-1', nome: 'Robótica Educacional' },
  { id: 'proj-2', nome: 'Iniciação Científica - Sensores' },
]

export const MOCK_EQUIPAMENTOS: Equipamento[] = [
  {
    id: '1',
    nome: 'Arduino Uno R3',
    codigo: 'EQ-001',
    fotoUrl: null,
    status: 'DISPONIVEL',
    laboratorio: 'Laboratório 2',
    bancada: 'Bancada 03',
    qtdDisponivel: 1,
    qtdTotal: 1,
    projeto: MOCK_PROJETOS[0],
  },
  {
    id: '2',
    nome: 'Protoboard 830 Pontos',
    codigo: 'EQ-002',
    fotoUrl: null,
    status: 'DISPONIVEL',
    laboratorio: 'Laboratório 1',
    bancada: 'Bancada 01',
    qtdDisponivel: 1,
    qtdTotal: 1,
    projeto: null,
  },
  {
    id: '3',
    nome: 'Motor Shield L298N',
    codigo: 'EQ-003',
    fotoUrl: null,
    status: 'EMPRESTADO',
    laboratorio: 'Laboratório 3',
    bancada: 'Bancada 02',
    qtdDisponivel: 1,
    qtdTotal: 3,
    projeto: MOCK_PROJETOS[0],
  },
  {
    id: '4',
    nome: 'Sensor Ultrassônico HC-SR04',
    codigo: 'EQ-004',
    fotoUrl: null,
    status: 'DISPONIVEL',
    laboratorio: 'Laboratório 1',
    bancada: null,
    qtdDisponivel: 1,
    qtdTotal: 1,
    projeto: MOCK_PROJETOS[1],
  },
  {
    id: '5',
    nome: 'Multímetro Digital',
    codigo: 'EQ-005',
    fotoUrl: null,
    status: 'MANUTENCAO',
    laboratorio: 'Laboratório 2',
    bancada: null,
    qtdDisponivel: 0,
    qtdTotal: 2,
    projeto: null,
  },
  {
    id: '6',
    nome: 'Osciloscópio Tektronix',
    codigo: 'EQ-006',
    fotoUrl: null,
    status: 'EMPRESTADO',
    laboratorio: 'Laboratório 2',
    bancada: null,
    qtdDisponivel: 0,
    qtdTotal: 1,
    projeto: null,
  },
  {
    id: '7',
    nome: 'Raspberry Pi 4',
    codigo: 'EQ-007',
    fotoUrl: null,
    status: 'INATIVO',
    laboratorio: 'Laboratório 3',
    bancada: null,
    qtdDisponivel: 0,
    qtdTotal: 4,
    projeto: MOCK_PROJETOS[1],
  },
  {
    id: '8',
    nome: 'Fonte de Bancada',
    codigo: 'EQ-008',
    fotoUrl: null,
    status: 'DISPONIVEL',
    laboratorio: 'Laboratório 2',
    bancada: null,
    qtdDisponivel: 2,
    qtdTotal: 2,
    projeto: null,
  },
]
