/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentIdRouteImport } from './routes/equipment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment': typeof EquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment/$id' | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipment/$id' | '/equipment'
  id: '__root__' | '/' | '/equipment/$id' | '/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentIdRoute: typeof EquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentIdRoute: EquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
